// ContextVarsUserStory/src/app/master-view/master-view.component.ts
import { Component, OnInit } from '@angular/core';
import { OrderDetailDto } from '../models/northwind-extended/order-detail-dto';
import { OrderDto } from '../models/northwind-extended/order-dto';
import { CustomerDto } from '../models/northwind-extended/customer-dto';
import { NorthwindExtendedService } from '../services/northwind-extended.service';

@Component({
  selector: 'app-master-view',
  templateUrl: './master-view.component.html',
  styleUrls: ['./master-view.component.scss']
})
export class MasterViewComponent implements OnInit {
  public northwindExtendedCustomerDto!: CustomerDto[];
  public northwindExtendedCustomerDto1!: CustomerDto[];
  public northwindExtendedOrderDto!: OrderDto[];
  public northwindExtendedOrderDetailDto!: OrderDetailDto[];

  public selectedCustomerID!: any;
  public selectedOrderID!: any;

  constructor(
    private northwindExtendedService: NorthwindExtendedService,
  ) {}

  ngOnInit() {
    // depending on implementation, data subscriptions might need to be unsubbed later
    this.northwindExtendedService.getCustomerDto().subscribe(data => this.northwindExtendedCustomerDto = data);
    this.northwindExtendedService.getCustomerDto().subscribe(data => this.northwindExtendedCustomerDto1 = data);
    this.northwindExtendedService.getOrderDto().subscribe(data => this.northwindExtendedOrderDto = data);
    this.northwindExtendedService.getOrderDetailDto().subscribe(data => this.northwindExtendedOrderDetailDto = data);
  }
}

<div class="column-layout group">
  <div class="row-layout group_1">
    <igx-simple-combo type="border" [data]="northwindExtendedCustomerDto" valueKey="customerId" displayKey="customerId" class="single-select-combo"></igx-simple-combo>
    <igx-grid [data]="northwindExtendedCustomerDto1" primaryKey="customerId" displayDensity="cosy" [allowFiltering]="true" filterMode="excelStyleFilter" class="grid">
      <igx-column field="customerId" dataType="string" header="customerId" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="companyName" dataType="string" header="companyName" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="contactName" dataType="string" header="contactName" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="contactTitle" dataType="string" header="contactTitle" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="address" dataType="string" header="address" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="city" dataType="string" header="city" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="region" dataType="string" header="region" [hidden]="true" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="postalCode" dataType="string" header="postalCode" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="country" dataType="string" header="country" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="phone" dataType="string" header="phone" [hidden]="true" [sortable]="true" [selectable]="false"></igx-column>
      <igx-column field="fax" dataType="string" header="fax" [hidden]="true" [sortable]="true" [selectable]="false"></igx-column>
    </igx-grid>
  </div>
  <div class="row-layout group_2">
    <div class="column-layout group_3">
      <h5 class="h5">
        Customer Details
      </h5>
      <igx-input-group type="border" *ngFor="let item of northwindExtendedCustomerDto" class="input">
        <input type="text" [(ngModel)]="item.companyName" [disabled]="true" igxInput />
        <label igxLabel>Company Name</label>
      </igx-input-group>
      <igx-input-group type="border" *ngFor="let item of northwindExtendedCustomerDto" class="input">
        <input type="text" [(ngModel)]="item.contactName" [disabled]="true" igxInput />
        <label igxLabel>Contract Name</label>
      </igx-input-group>
      <igx-input-group type="border" *ngFor="let item of northwindExtendedCustomerDto" class="input">
        <input type="text" [(ngModel)]="item.contactTitle" [disabled]="true" igxInput />
        <label igxLabel>Contract Title</label>
      </igx-input-group>
      <igx-input-group type="border" *ngFor="let item of northwindExtendedCustomerDto" class="input">
        <input type="text" [(ngModel)]="item.address" [disabled]="true" igxInput />
        <label igxLabel>Address</label>
      </igx-input-group>
      <igx-input-group type="border" *ngFor="let item of northwindExtendedCustomerDto" class="input">
        <input type="text" [(ngModel)]="item.city" [disabled]="true" igxInput />
        <label igxLabel>City</label>
      </igx-input-group>
      <igx-input-group type="border" *ngFor="let item of northwindExtendedCustomerDto" class="input">
        <input type="text" [(ngModel)]="item.country" [disabled]="true" igxInput />
        <label igxLabel>Country</label>
      </igx-input-group>
    </div>
    <div class="column-layout group_4">
      <div class="row-layout group_5">
        <h5 class="h5">
          Showing orders for:
        </h5>
        <h5 class="h5_1">
          {{ selectedCustomerID }}
        </h5>
      </div>
      <igx-grid [data]="northwindExtendedOrderDto" primaryKey="orderId" displayDensity="cosy" rowSelection="single" [allowFiltering]="true" filterMode="excelStyleFilter" height="45%" class="grid_1">
        <igx-column field="orderId" dataType="number" header="orderId" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="customerId" dataType="string" header="customerId" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="employeeId" dataType="number" header="employeeId" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="orderDate" dataType="date" header="orderDate" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="requiredDate" dataType="date" header="requiredDate" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shippedDate" dataType="date" header="shippedDate" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipVia" dataType="number" header="shipVia" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="freight" dataType="number" header="freight" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipName" dataType="string" header="shipName" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipAddress" dataType="string" header="shipAddress" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipCity" dataType="string" header="shipCity" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipRegion" dataType="string" header="shipRegion" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipPostalCode" dataType="string" header="shipPostalCode" [sortable]="true" [selectable]="false"></igx-column>
        <igx-column field="shipCountry" dataType="string" header="shipCountry" [sortable]="true" [selectable]="false"></igx-column>
      </igx-grid>
      <div class="row-layout group_5">
        <h5 class="h5">
          Showing order details for:
        </h5>
        <h5 class="h5_1">
          {{ selectedOrderID }}
        </h5>
      </div>
      <div class="row-layout group_6">
        <igx-grid [data]="northwindExtendedOrderDetailDto" primaryKey="orderId" displayDensity="cosy" [allowFiltering]="true" filterMode="excelStyleFilter" width="70%" height="100%" class="grid_1">
          <igx-column field="orderId" dataType="number" header="orderId" [sortable]="true" [selectable]="false"></igx-column>
          <igx-column field="productId" dataType="number" header="productId" [sortable]="true" [selectable]="false"></igx-column>
          <igx-column field="unitPrice" dataType="number" header="unitPrice" [sortable]="true" [selectable]="false"></igx-column>
          <igx-column field="quantity" dataType="number" header="quantity" [sortable]="true" [selectable]="false"></igx-column>
          <igx-column field="discount" dataType="number" header="discount" [sortable]="true" [selectable]="false"></igx-column>
        </igx-grid>
        <igx-pie-chart [dataSource]="northwindExtendedOrderDetailDto" labelMemberPath="productId" valueMemberPath="quantity" class="pie-chart"></igx-pie-chart>
      </div>
    </div>
  </div>
</div>

// ContextVarsUserStory_WC/src/app/master-view/master-view.ts
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { defineComponents, IgcComboComponent, IgcInputComponent } from 'igniteui-webcomponents';
import { IgcPieChartModule } from 'igniteui-webcomponents-charts';
import { ModuleManager } from 'igniteui-webcomponents-core';
import 'igniteui-webcomponents-grids/grids/combined.js';
import { OrderDto } from '../models/northwind-extended/order-dto';
import { CustomerDto } from '../models/northwind-extended/customer-dto';
import { OrderDetailDto } from '../models/northwind-extended/order-detail-dto';
import NorthwindExtendedService from '../services/NorthwindExtended-service';

defineComponents(IgcComboComponent, IgcInputComponent);

ModuleManager.register(IgcPieChartModule);

@customElement('app-master-view')
export default class MasterView extends LitElement {
  static styles = css`
    :host {
      height: 100%;
      display: flex;
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
    }
    .column-layout {
      display: flex;
      flex-direction: column;
    }
    .group {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      min-width: 50px;
      min-height: 50px;
      flex-grow: 1;
      flex-basis: 0;
    }
    .row-layout {
      display: flex;
    }
    .group_1 {
      background-color: hsla(var(--ig-gray-100));
      justify-content: flex-start;
      align-items: center;
      align-content: flex-start;
      gap: 15px;
      position: relative;
      padding: 20px;
      height: 17%;
      min-width: 50px;
      min-height: 50px;
    }
    .group_2 {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      padding: 16px;
      height: 83%;
      min-width: 50px;
      min-height: 50px;
    }
    .group_3 {
      background-color: hsla(var(--ig-gray-100));
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      gap: 16px;
      position: relative;
      padding: 16px;
      width: 20%;
      min-width: 50px;
      min-height: 50px;
    }
    .group_4 {
      background-color: transparent;
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      padding: 16px;
      width: 80%;
      min-width: 50px;
      min-height: 50px;
    }
    .group_5 {
      justify-content: flex-start;
      align-items: center;
      align-content: flex-start;
      gap: 8px;
      position: relative;
      height: 5%;
      min-width: 50px;
      min-height: 50px;
    }
    .group_6 {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      gap: 15px;
      position: relative;
      height: 45%;
      min-width: 50px;
      min-height: 50px;
    }
    .single-select-combo {
      height: max-content;
      min-width: min-content;
      flex-shrink: 0;
    }
    .input {
      height: max-content;
      min-width: min-content;
    }
    .grid {
      min-width: 600px;
      min-height: 85px;
      flex-grow: 1;
      flex-basis: 0;
    }
    .grid_1 {
      min-width: 600px;
      min-height: 100px;
    }
    .h5 {
      height: max-content;
      min-width: min-content;
    }
    .h5_1 {
      color: hsla(var(--ig-secondary-700));
      height: max-content;
      min-width: min-content;
    }
    .pie-chart {
      width: 30%;
      min-width: 150px;
      min-height: 150px;
    }
  `;

  constructor() {
    super();
    this.northwindExtendedService.getCustomerDto().then((data) => {
      this.northwindExtendedCustomerDto = data;
    }, err => console.log(err));
    this.northwindExtendedService.getOrderDto().then((data) => {
      this.northwindExtendedOrderDto = data;
    }, err => console.log(err));
    this.northwindExtendedService.getOrderDetailDto().then((data) => {
      this.northwindExtendedOrderDetailDto = data;
    }, err => console.log(err));
  }

  private northwindExtendedService: NorthwindExtendedService = new NorthwindExtendedService();

  @property()
  private northwindExtendedCustomerDto?: CustomerDto;

  @property()
  private northwindExtendedOrderDto?: OrderDto[];

  @property()
  private northwindExtendedOrderDetailDto?: OrderDetailDto[];

  render() {
    return html`
      <link rel='stylesheet' href='../../ig-theme.css'>
      <link rel='stylesheet' href='node_modules/igniteui-webcomponents-grids/grids/themes/light/material.css'>
      <div class="column-layout group">
        <div class="row-layout group_1">
          <igc-combo ?outlined="${true}" .data="${this.northwindExtendedCustomerDto}" value-key="customerId" display-key="customerId" ?single-select="${true}" class="single-select-combo"></igc-combo>
          <igc-grid .data="${this.northwindExtendedCustomerDto}" primary-key="customerId" display-density="cosy" allow-filtering="true" filter-mode="excelStyleFilter" auto-generate="false" class="ig-typography ig-scrollbar grid">
            <igc-column field="customerId" data-type="string" header="customerId" sortable="true" selectable="false"></igc-column>
            <igc-column field="companyName" data-type="string" header="companyName" sortable="true" selectable="false"></igc-column>
            <igc-column field="contactName" data-type="string" header="contactName" sortable="true" selectable="false"></igc-column>
            <igc-column field="contactTitle" data-type="string" header="contactTitle" sortable="true" selectable="false"></igc-column>
            <igc-column field="address" data-type="string" header="address" sortable="true" selectable="false"></igc-column>
            <igc-column field="city" data-type="string" header="city" sortable="true" selectable="false"></igc-column>
            <igc-column field="region" data-type="string" header="region" sortable="true" selectable="false"></igc-column>
            <igc-column field="postalCode" data-type="string" header="postalCode" sortable="true" selectable="false"></igc-column>
            <igc-column field="country" data-type="string" header="country" sortable="true" selectable="false"></igc-column>
            <igc-column field="phone" data-type="string" header="phone" sortable="true" selectable="false"></igc-column>
            <igc-column field="fax" data-type="string" header="fax" sortable="true" selectable="false"></igc-column>
          </igc-grid>
        </div>
        <div class="row-layout group_2">
          <div class="column-layout group_3">
            <h5 class="h5">
              Customer Details
            </h5>
            ${this.northwindExtendedCustomerDto?.map((item) => html`
              <igc-input .value="${item.companyName}" label="Company Name" ?disabled="${true}" ?outlined="${true}" class="input"></igc-input>
            `)}
            ${this.northwindExtendedCustomerDto?.map((item) => html`
              <igc-input .value="${item.contactName}" label="Contract Name" ?disabled="${true}" ?outlined="${true}" class="input"></igc-input>
            `)}
            ${this.northwindExtendedCustomerDto?.map((item) => html`
              <igc-input .value="${item.contactTitle}" label="Contract Title" ?disabled="${true}" ?outlined="${true}" class="input"></igc-input>
            `)}
            ${this.northwindExtendedCustomerDto?.map((item) => html`
              <igc-input .value="${item.address}" label="Address" ?disabled="${true}" ?outlined="${true}" class="input"></igc-input>
            `)}
            ${this.northwindExtendedCustomerDto?.map((item) => html`
              <igc-input .value="${item.city}" label="City" ?disabled="${true}" ?outlined="${true}" class="input"></igc-input>
            `)}
            ${this.northwindExtendedCustomerDto?.map((item) => html`
              <igc-input .value="${item.country}" label="Country" ?disabled="${true}" ?outlined="${true}" class="input"></igc-input>
            `)}
          </div>
          <div class="column-layout group_4">
            <div class="row-layout group_5">
              <h5 class="h5">
                Showing orders for:
              </h5>
              <h5 class="h5_1">
                selectedCustomerID
              </h5>
            </div>
            <igc-grid .data="${this.northwindExtendedOrderDto}" primary-key="orderId" display-density="cosy" row-selection="single" allow-filtering="true" filter-mode="excelStyleFilter" auto-generate="false" height="45%" class="ig-typography ig-scrollbar grid_1">
              <igc-column field="orderId" data-type="number" header="orderId" sortable="true" selectable="false"></igc-column>
              <igc-column field="customerId" data-type="string" header="customerId" sortable="true" selectable="false"></igc-column>
              <igc-column field="employeeId" data-type="number" header="employeeId" sortable="true" selectable="false"></igc-column>
              <igc-column field="orderDate" data-type="date" header="orderDate" sortable="true" selectable="false"></igc-column>
              <igc-column field="requiredDate" data-type="date" header="requiredDate" sortable="true" selectable="false"></igc-column>
              <igc-column field="shippedDate" data-type="date" header="shippedDate" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipVia" data-type="number" header="shipVia" sortable="true" selectable="false"></igc-column>
              <igc-column field="freight" data-type="number" header="freight" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipName" data-type="string" header="shipName" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipAddress" data-type="string" header="shipAddress" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipCity" data-type="string" header="shipCity" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipRegion" data-type="string" header="shipRegion" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipPostalCode" data-type="string" header="shipPostalCode" sortable="true" selectable="false"></igc-column>
              <igc-column field="shipCountry" data-type="string" header="shipCountry" sortable="true" selectable="false"></igc-column>
            </igc-grid>
            <div class="row-layout group_5">
              <h5 class="h5">
                Showing order details for:
              </h5>
              <h5 class="h5_1">
                selectedOrderID
              </h5>
            </div>
            <div class="row-layout group_6">
              <igc-grid .data="${this.northwindExtendedOrderDetailDto}" primary-key="orderId" display-density="cosy" allow-filtering="true" filter-mode="excelStyleFilter" auto-generate="false" width="70%" height="100%" class="ig-typography ig-scrollbar grid_1">
                <igc-column field="orderId" data-type="number" header="orderId" sortable="true" selectable="false"></igc-column>
                <igc-column field="productId" data-type="number" header="productId" sortable="true" selectable="false"></igc-column>
                <igc-column field="unitPrice" data-type="number" header="unitPrice" sortable="true" selectable="false"></igc-column>
                <igc-column field="quantity" data-type="number" header="quantity" sortable="true" selectable="false"></igc-column>
                <igc-column field="discount" data-type="number" header="discount" sortable="true" selectable="false"></igc-column>
              </igc-grid>
              <igc-pie-chart .dataSource="${this.northwindExtendedOrderDetailDto}" label-member-path="orderId" value-member-path="orderId" class="pie-chart"></igc-pie-chart>
            </div>
          </div>
        </div>
      </div>
    `;
  }
}
